### ISSUE TITLE
Not correct image saving

### ISSUE THREAD

**Issue by pro100Hub** [Dezaimasu/cute-button#21]
Firefox 72

Hello.
For example, using [this link](https://www.banggood.com/EU-Asia-Frequency-Version-Original-Box-CHUWI-Hi9-Plus-128GB-MT6797X-Helio-X27-Deca-Core-10_8-Inch-2_5K-Screen-Android-8_0-Dual-4G-Tablet-p-1484720.html) if you save images from the description, the extension of these files will be with the prefix .webp
Also, some images are saved without previews. They cannot be opened in Photoshop. You can check [this link](https://aliexpress.ru/item/4000044517119.html).
Please fixed.

Regards.

**Comment by Dezaimasu** [comment]
Sorry, can't help you. 

In case of banggood, there's only webp image available . I _can_ get jpg image by adding specific hack for this specific site, but I'm not interested in bloating my code with hacks for chinese shops. Sorry.

In case of aliexpress, you can't see previews and can't open them with PS because those are actually WebP images as well. Those are not JPEG images, even though they are saved with .jpg extension. WebP images can't be opened with PS (at least my version can't). Windows (at least 7) can't work with WebP images, thus no previews.

![Capture](https://user-images.githubusercontent.com/1636242/84433501-0bd66480-ac37-11ea-8696-cfa2c39c946d.PNG)

You can thank Google LLC for such an amazing format with close to none support outside of web. I really wish I could help you, but stupid people with money is an unbeatable combo. Just embrace the inevitable.

**Comment by sjf2** [comment]
Would it be possible to add two additional "Button Positions" to the options.  The positions would be "Middle-Right" and "Middle-Left".  Very often I download images from websites that have an arrow midway down the picture that advances the image. When using Cute-Button, I click to advance the image then have to move my mouse cursor to the Cute-Button which I can only position at the top or the bottom.  Having the ability to position the button in the middle would allow for a much smaller mouse cursor movement and would reduce the occurrence of missed clicks and therefore unwanted image advances.
Thank you very much!
P.S.  I really, really love your extension. It allows me to download images which would otherwise be unavailable via right-click options.  Would it be possible to add this add-on to the Android versions of Firefox and Chrome?

**Comment by Dezaimasu** [comment]
@sjf2
You can use this option, was added recently. Set offset to something like 200px
![image](https://user-images.githubusercontent.com/1636242/115960276-20eb7780-a519-11eb-8784-ec99f78471b9.png)
