### ISSUE TITLE
Tumblr Photoset Dupe Issue

### ISSUE THREAD

**Issue by RedBreloom** [Dezaimasu/cute-button#29]
I have long been running into an issue of getting a lot of dupilcate versions of one or a few images when using the Cute button on tumblr. I finally realized and managed to recreate the issue consistently: 
Tumblr phototsets (which is to say, at least 2 images) allow you to click on the right or left side to go forward and back in a set. If you save a picture in that set with the Cute button and then quickly move through to any other image, there is a high chance it will be download duplicate images and not the intended new ones. Sometimes it happened while using the Cute button on other images in the set. Sometimes it seemed to interpret the clicks between pictures as a click on the Cute button for the duplicated picture as well. This seems to be mainly if the cute button is used on other images as well.
Let me know if you need any other information.

Also wanted to throw the request of full resolution downloads of the sites zerochan or safebooru if possible? It'd be useful to use the button and also avoid having to click through 2-3 times to download the fullest size version.

**Comment by RedBreloom** [comment]
oh and the save button is located in the lower left part of the photos for me, if that matters at all.

**Comment by RedBreloom** [comment]
I am not sure the status of the bug but I can report that the issue is not present if tumblr photos in a photoset are individually opened and closed between each button download.

**Comment by Dezaimasu** [comment]
For now you can try "No duplicates" option. I'll get to this bug when I have time.

**Comment by RedBreloom** [comment]
Yeah no worries, just giving extra info. And the bug also ignores 'no dupes' being active.

**Comment by Dezaimasu** [comment]
About boorus, you were talking about clicking here, on thumbnail in gallery
![image](https://user-images.githubusercontent.com/1636242/116491094-bbddac00-a8a1-11eb-84a0-5b816e218d07.png)
or here, on still-not-original-size image on its page
![image](https://user-images.githubusercontent.com/1636242/116491120-cb5cf500-a8a1-11eb-8c83-748f828e73ed.png)
Because both are possible, but the button won't appear on small thumbnails with default settings, so I'm not sure which case you were talking about.

**Comment by RedBreloom** [comment]
I was referring to the not-quite-original size images. To save having to click them like three times for the full res once on the page.
Thanks btw I really appreciate this button. Especially since firefox doesn't seem to have the simple google chrome shortcut to download on click +alt or something. This is better anyway cos it can pull full-res automatically too for a bunch of sites I use.

**Comment by RedBreloom** [comment]
I notice tumblr isn't downloading full res images without clicking through to it and instagram downloads (click from posts) are failing? 
I haven't been on them very much lately so I didn't notice this issue.

**Comment by Dezaimasu** [comment]
Stopped using tumblr long ago, looks like they completely changed url generation algorithm. I'll check what can be done but can't promise anything.

**Comment by Dezaimasu** [comment]
New version is published, please check if everything works as it should and report any bugs.
Keep in mind, button is kinda laggy on tumblr now because I have to make additional request to get original image, and I was too lazy to make it synchronous, but I'll try to fix it asap.

**Comment by RedBreloom** [comment]
I've tested numerous conditions for the image size downloads and have info on all of them pretty much:

Art in photosets that affect the piece's size affect the download size. Example: There are four art pieces are side by side in a photoset and are all auto resized to fit on the post/dash. Downloading from this state (not clicked on for enlarged view) has the image download the photo at the smaller size. I.E.- the 724x500 version will be downloaded even if there is a larger (say, 1000x765) if you click on it. Even minimally resized images will yield the smaller size. Clicking on it and then downloading using the button yields the full res image.

Photosets can duplicate or get confused still, but i found a workaround. If you click on a photoset and download using the button then click on the next image itself (not the current image) to advance and dl, then it works fine.

I appreciate your work on this.

**Comment by Dezaimasu** [comment]
Could you give me the link for some photoset like that?
The problem is, old images and new images have completely different urls, also different pages may have or don't have info about all available sizes, so it's kinda hard to tell what is happening.
Also I'm pretty sure my current solution (it works for me at least) won't last long and tumblr will break something again.

**Comment by RedBreloom** [comment]
Yeah tumblr totally rebuilt their dashboard and stuff with React i think? sometime last year. 

[](https://tilthedayidice.tumblr.com/post/650473357121290240/archerinventive-journals-a-little-while-ago)
Here's a really recent one (3 hours old). I tested on the ones that are cropped/two next to each other for testing.
I can find one from a year or two ago if that'd be helpful as well.

**Comment by Dezaimasu** [comment]
Are you sure you're using the latest version, 0.8.0? Because it always downloads full-sized version for me. I even tested it using clean Firefox profile with default settings, still works as intended. What version of Firefox are you using?

https://user-images.githubusercontent.com/1636242/117517244-18c51a80-afa4-11eb-92ea-2b55607f9aff.mp4

**Comment by RedBreloom** [comment]
Oh huh, I guess it hadn't updated the addon until today. Not sure why it wasn't working right before, but It works now! And is on the newest version. I'm happy about this yay. And hopefully tumblr doesn't break it too soon.
